/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnilib_NDKString */

#ifndef _Included_com_example_jnilib_NDKString
#define _Included_com_example_jnilib_NDKString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnilib_NDKString
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnilib_NDKString_getName
  (JNIEnv *, jclass){
                      return name->NewStringUTF("第一个");
                      };
#ifdef __cplusplus
}
#endif
#endif
